### ISSUE TITLE
Buttons Back doesn't work again.

### ISSUE THREAD

**Issue by suishouen** [darktrojan/buttonsback#4]
Mozilla-central/changeset/79f6ba23157e (https://hg.mozilla.org/mozilla-central/rev/79f6ba23157e) seems to break Buttons Back again.

Thanks.

**Comment by suishouen** [comment]
In addition Mozilla has changed Toolbar Icons from PNG to SVG.
See Bug 1347543: https://bugzilla.mozilla.org/show_bug.cgi?id=1347543.

**Comment by jtojnar** [comment]
Since [1364090](https://bugzilla.mozilla.org/show_bug.cgi?id=1364090) landed, it looks like I no longer need this extension – the refresh button has returned to its proper place. Thank you, darktrojan, for keeping our sanity during the dark times.

**Comment by darktrojan** [comment]
Well, that's "progress" for you!

**Comment by suishouen** [comment]
In Firefox 56.0a1, the reload and stop buttons remain in the toolbar.
In Firefox 55.0b2, the reload and stop buttons are placed back in the location bar.

So I remove
1) xul parts as below except script parts from /content/overlay.xul 
```
<toolbaritem id="urlbar-container">
		<toolbarbutton
			id="reload-button"
			class="toolbarbutton-1 chromeclass-toolbar-additional"
			label="&reloadCmd.label;"
			command="Browser:ReloadOrDuplicate"
			onclick="checkForMiddleClick(this, event);"
			oncommand="BrowserReloadOrDuplicate(event);" />
		<toolbarbutton
			id="stop-button"
			class="toolbarbutton-1 chromeclass-toolbar-additional"
			label="&stopCmd.label;"
			command="Browser:Stop"
			oncommand="BrowserStop();" />
</toolbaritem>
```

2) /skin/osx/style.css

and repack all the files.

That seems to work fine on Firefox 55.0b2 and Firefox 56.0a1.
I'm not a coder and I only tested it on macOS, so would you please confirm that?

**Comment by darktrojan** [comment]
Sigh.

Just made a fixed version for 55 since it's now in beta. Should be available when it's reviewed.

**Comment by suishouen** [comment]
Thanks so much for a fix.
